import java.util.Properties

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    `maven-publish`
}

group = providers.gradleProperty("GROUP").get()
version = providers.gradleProperty("VERSION_NAME").get()

val publishedArtifactId = providers.gradleProperty("POM_ARTIFACT_ID").get()
val localProperties = Properties().apply {
    rootProject.file("local.properties")
        .takeIf { it.isFile }
        ?.inputStream()
        ?.use(::load)
}
val githubPackagesUsername = providers.gradleProperty("github.packages.username")
    .orElse(providers.environmentVariable("GITHUB_PACKAGES_USERNAME"))
    .orElse(providers.provider { localProperties.getProperty("github.packages.username").orEmpty() })
val githubPackagesToken = providers.gradleProperty("github.packages.token")
    .orElse(providers.environmentVariable("GITHUB_PACKAGES_TOKEN"))
    .orElse(providers.provider { localProperties.getProperty("github.packages.token").orEmpty() })

android {
    namespace = "com.cashcraft.ads.mediation"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
        consumerProguardFiles("consumer-rules.pro")
    }

    buildFeatures {
        buildConfig = true
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }
}

configurations.configureEach {
    // GMA Next-Gen supplies the mediation API classes. Never package the legacy SDK beside it.
    exclude(group = "com.google.android.gms", module = "play-services-ads")
    exclude(group = "com.google.android.gms", module = "play-services-ads-lite")
}

dependencies {
    // Direct AdMob provider + TopOn's GMA Next-Gen network adapter.
    implementation(libs.ads.mobile.sdk)
    // GMA Next-Gen 1.2.1 still declares WorkManager 2.7.0/Room 2.2.5. With
    // current R8 those old Room rules can lose WorkDatabase_Impl's reflective
    // constructor and crash the host before Application.onCreate().
    implementation(libs.androidx.work.runtime)
    implementation(libs.user.messaging.platform)
    implementation(libs.topon.gma.nextgen.adapter)

    // TopOn TU core and the exact network set generated by the TopOn console.
    implementation(libs.topon.core)
    implementation(libs.topon.adx.adapter)
    implementation(libs.topon.adx.sdk)
    implementation(libs.topon.pangle.adapter)
    implementation(libs.pangle.sdk)
    implementation(libs.play.services.ads.identifier)
    implementation(libs.topon.facebook.adapter)
    implementation(libs.facebook.audience.network)
    implementation(libs.topon.androidx.annotation)
    implementation(libs.topon.mintegral.adapter)
    implementation(libs.mintegral.sdk)
    implementation(libs.androidx.recyclerview)
    implementation(libs.topon.media3.exoplayer)
    implementation(libs.topon.media3.ui)
    implementation(libs.topon.retrofit.kotlinx.converter)
    implementation(libs.topon.okhttp.logging)
    implementation(libs.okhttp)
    implementation(libs.topon.retrofit.scalars)
    implementation(libs.topon.retrofit.core)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.topon.tramini)

    // Required by the TU core integration guide.
    implementation(libs.androidx.appcompat)
    implementation(libs.topon.androidx.browser)
    implementation(libs.androidx.core.ktx)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
}

afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("release") {
                from(components["release"])
                groupId = project.group.toString()
                artifactId = publishedArtifactId
                version = project.version.toString()
                pom {
                    name.set("Ads Mediation")
                    description.set(
                        "Android mediation for AdMob Next-Gen, TopOn, and cached-price bidding.",
                    )
                    url.set("https://github.com/vihuela/ads-mediation")
                    licenses {
                        license {
                            name.set("Proprietary")
                            distribution.set("repo")
                        }
                    }
                    scm {
                        url.set("https://github.com/vihuela/ads-mediation")
                        connection.set("scm:git:https://github.com/vihuela/ads-mediation.git")
                        developerConnection.set("scm:git:ssh://git@github.com/vihuela/ads-mediation.git")
                    }
                }
            }
        }
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/vihuela/ads-mediation")
                credentials {
                    username = githubPackagesUsername.orNull
                    password = githubPackagesToken.orNull
                }
            }
        }
    }
}
